config/routes.rb
WolfPackApp::Application.routes.draw do
  resources :wolf_packs, only: [:new, :create, :show] do
    resources :events
    member do
      get 'join'
      get 'leave'
      post 'add_resource'
      post 'add_answer'
      put 'upvote_answer'
      put 'downvote_answer'
      post 'add_event'
    end
  end
  resources :events, only: [:show]

  devise_for :users, skip: [:sessions, :registrations]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    post 'signup' => 'devise/registrations#create', :as => :user_registration
    get 'profile' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'profile' => 'devise/registrations#update', :as => :user_registration
    delete 'oust' => 'devise/registrations#destroy', :as => :destroy_user_registration
  end

  root :to => "home#index"

  
end

app/models/wolf_pack.rb
class WolfPack < ActiveRecord::Base
  attr_accessible :location, :name
  default_scope order: [:location, :name]

  has_many :events, dependent: :destroy
  has_many :resources, dependent: :destroy
  has_and_belongs_to_many :users

  def title
    "[#{location}] #{name}"
  end
end

app/controllers/wolf_packs_controller.rb
class WolfPacksController < ApplicationController

  def new
    @wolf_pack = WolfPack.new
  end

  def create
    @wolf_pack = WolfPack.new params[:wolf_pack]
    if @wolf_pack.save
      redirect_to @wolf_pack, notice: 'Wolf pack was successfully created.'
    else
      render action: "new"
    end
  end

  def show
    @wolf_pack = WolfPack.find params[:id]
  end

  def join
    @wolf_pack = WolfPack.find params[:id]
    @wolf_pack.users.push @user
    redirect_to @wolf_pack
  end

  def leave
    @wolf_pack = WolfPack.find params[:id]
    @wolf_pack.users.delete @user
    redirect_to @wolf_pack
  end

  def add_resource
    @wolf_pack = WolfPack.find params[:id]
    @wolf_pack.resources.create params[:resource]
    redirect_to @wolf_pack
  end

  # def upvote_resource
  #   @wolf_pack = WolfPack.find params[:id]
  #   @answer = Answer.find params[:answer_id]
  #   @answer.update_attribute(:votes, @answer.votes+1)
  #   render nothing: true
  # end

  # def downvote_resource
  #   @wolf_pack = WolfPack.find params[:id]
  #   @answer = Answer.find params[:answer_id]
  #   @answer.update_attribute(:votes, @answer.votes-1)
  #   render nothing: true
  # end

  def add_answer
    @wolf_pack = WolfPack.find params[:id]
    Answer.create params[:answer]
    redirect_to @wolf_pack
  end

  def upvote_answer
    @wolf_pack = WolfPack.find params[:id]
    @answer = Answer.find params[:answer_id]
    @answer.update_attribute(:votes, @answer.votes+1)
    render text: "$('#answer_#{@answer.id}_votes').text(#{@answer.votes});"
  end

  def downvote_answer
    @wolf_pack = WolfPack.find params[:id]
    @answer = Answer.find params[:answer_id]
    @answer.update_attribute(:votes, @answer.votes-1)
    render text: "$('#answer_#{@answer.id}_votes').text(#{@answer.votes});"
  end

  def add_event
    @wolf_pack = WolfPack.find params[:id]
    event = @wolf_pack.events.create params[:event]
    resource = Resource.new category: "event", description: event.name, url: event.id
    @wolf_pack.resources.push resource
    redirect_to @wolf_pack
  end

end

app/helpers/wolf_packs_helper.rb
module WolfPacksHelper
end

app/views/wolf_packs/new.html.erb
<h1>New Pack</h1>

<%= form_for(@wolf_pack) do |f| %>
  <% if @wolf_pack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wolf_pack.errors.count, "error") %> prohibited this wolf_pack from being saved:</h2>

      <ul>
      <% @wolf_pack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit "Create Pack", class: "btn btn-info" %>
  </div>
<% end %>

app/views/wolf_packs/show.haml
- content_for :head do
  :javascript
    $(document).ready(function() {
      $("input#event_date").datepicker({
        dateFormat: $.datepicker.ISO_8601, 
        minDate: "#{Date.today}"
      });
      $("input#event_start_time").timepicker();
      $("input#event_end_time").timepicker();
    });

.row-fluid
  .span6
    %h2{style: "float: left;"}= @wolf_pack.name
    %h3{style: "float: left; padding: 3px 0 0 6px; color: #999"}= @wolf_pack.location
  .span6
    - if @wolf_pack.users.include? @user
      = link_to "Leave", leave_wolf_pack_url(@wolf_pack), class: "btn btn-danger"
    - else
      = link_to "Join", join_wolf_pack_url(@wolf_pack), class: "btn btn-large btn-primary"
.feed-container
  %ul.nav.nav-tabs
    %li.active= link_to "Howl", "#question-form", "data-toggle" => "tab"
    %li= link_to "Feed", "#external-form", "data-toggle" => "tab"
    %li= link_to "Meet", "#event-form", "data-toggle" => "tab"
  .tab-content
    #question-form.tab-pane.active
      = form_for Resource.new, url: add_resource_wolf_pack_url(@wolf_pack), method: :post do |f|
        = f.hidden_field :category, value: "question"
        = f.hidden_field :user_id, value: @user.id
        = f.text_area :description, rows: 3, placeholder: "Ask anything!", style: "width: 430px;"
        %br
        = f.submit "Howl", class: "btn btn-info"
    #external-form.tab-pane
      = form_for Resource.new, url: add_resource_wolf_pack_url(@wolf_pack), method: :post do |f|
        = f.hidden_field :category, value: "external"
        = f.hidden_field :user_id, value: @user.id
        = f.text_field :url, placeholder: "Resource URL", style: "width: 430px;"
        %br
        = f.text_area :description, rows: 3, placeholder: "Description", style: "width: 430px;"
        %br
        = f.submit "Feed", class: "btn btn-info"
    #event-form.tab-pane
      = form_for Event.new, url: add_event_wolf_pack_url(@wolf_pack), method: :post do |f|
        = f.hidden_field :user_id, value: @user.id
        = f.text_field :name, placeholder: "Name", style: "width: 430px;"
        %br
        = f.text_area :description, rows: 3, placeholder: "Description", style: "width: 430px;"
        %br
        = f.text_field :date, placeholder: "Date"
        = f.text_field :start_time, placeholder: "Start", style: "width: 94px"
        = f.text_field :end_time, placeholder: "End", style: "width: 94px"
        %br
        = f.submit "Meet", class: "btn btn-info"

  
    - @wolf_pack.resources.each do |resource|
      .resource{id: "resource_#{resource.id}"}
        - if resource.category == "question"
          .howl
            .question
              %i.icon-question-sign
              = resource.description
            - resource.answers.each do |answer|
              .answer
                = link_to uvi, upvote_answer_wolf_pack_url(@wolf_pack, answer_id: answer.id), method: :put, remote: true
                %span{id: "answer_#{answer.id}_votes"}= answer.votes
                = link_to dvi, downvote_answer_wolf_pack_url(@wolf_pack, answer_id: answer.id), method: :put, remote: true
              
                = answer.description
            .answer-form
              = form_for Answer.new, url: add_answer_wolf_pack_url(@wolf_pack) do |f|
                = f.hidden_field :resource_id, value: resource.id
                = f.hidden_field :user_id, value: @user.id
                = f.text_area :description, rows: 2, placeholder: "Reply", style: "width:380px;"
                = f.submit "Post", class: "btn btn-info"
        - elsif resource.category == "event"
          .event
            %a.clearfix{href: event_url(resource.url)}
              %h3{style: "float: left;"}= resource.description
              %div{style: "float: left; padding: 22px 0 0 6px;"}= Event.find(resource.url).date.strftime("%d %B %Y")
            = Event.find(resource.url).description
        - elsif resource.category == "external"
          - og = OpenGraph.fetch(resource.url)
          - if og && og["type"] == "video"
            .video
              %h3.video-discription  
                = resource.description
              .video-image
                %a{href: "#video_#{resource.id}", "data-toggle" => "modal"}
                  = image_tag og["image"] unless og["image"].blank?
            .modal.hide{id: "video_#{resource.id}", style: "width: 600px; height: 400px;"}
              %iframe{src: og["video"], style: "width: 600px; height: 400px;"}
          - else
            .unrecognized
              %a{href: resource.url}
                %h4= resource.description
                = image_tag og["image"] unless !og || og["image"].blank?