config/routes.rb
WolfPackApp::Application.routes.draw do
  resources :wolf_packs, only: [:new, :create, :show] do
    resources :events
    member do
      get 'join'
      get 'leave'
      post 'add_resource'
      post 'add_answer'
      put 'upvote_answer'
      put 'downvote_answer'
      post 'add_event'
    end
  end
  resources :events, only: [:show]

  devise_for :users, skip: [:sessions, :registrations]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    post 'signup' => 'devise/registrations#create', :as => :user_registration
    get 'profile' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'profile' => 'devise/registrations#update', :as => :user_registration
    delete 'oust' => 'devise/registrations#destroy', :as => :destroy_user_registration
  end

  root :to => "home#index"

  
end

app/views/wolf_packs.original/_form.html.erb
<%= form_for(@wolf_pack) do |f| %>
  <% if @wolf_pack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wolf_pack.errors.count, "error") %> prohibited this wolf_pack from being saved:</h2>

      <ul>
      <% @wolf_pack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wolf_packs.original/edit.html.erb
<h1>Editing wolf_pack</h1>

<%= render 'form' %>

<%= link_to 'Show', @wolf_pack %> |
<%= link_to 'Back', wolf_packs_path %>

app/views/wolf_packs.original/index.html.erb
<h1>Listing wolf_packs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wolf_packs.each do |wolf_pack| %>
  <tr>
    <td><%= wolf_pack.name %></td>
    <td><%= wolf_pack.location %></td>
    <td><%= link_to 'Show', wolf_pack %></td>
    <td><%= link_to 'Edit', edit_wolf_pack_path(wolf_pack) %></td>
    <td><%= link_to 'Destroy', wolf_pack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wolf pack', new_wolf_pack_path %>

app/views/wolf_packs.original/new.html.erb
<h1>New wolf_pack</h1>

<%= render 'form' %>

<%= link_to 'Back', wolf_packs_path %>

app/views/wolf_packs.original/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @wolf_pack.name %>
</p>

<p>
  <b>Location:</b>
  <%= @wolf_pack.location %>
</p>


<%= link_to 'Edit', edit_wolf_pack_path(@wolf_pack) %> |
<%= link_to 'Back', wolf_packs_path %>